repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: end-of-file-fixer
        exclude: ^.+/(test/resources|resources/db)/.+$
    -   id: trailing-whitespace
        exclude: ^.+/(test/resources|resources/db)/.+$
-   repo: git://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.9
    hooks:
    -   id: remove-crlf
        exclude: ^.+/(test/resources|resources/db)/.+$
    -   id: remove-tabs
        args: [ --whitespaces-count=2 ]
        exclude: ^.+/(test/resources|resources/db)/.+$
-   repo: git@github.com:extenda/pre-commit-hooks.git
    rev: v0.4
    hooks:
    -   id: google-java-formatter
